// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { logAuthStage } from "@/lib/auth-diagnostics";
import { supabase } from "../supabase/client";
import { establishOAuthSession } from "./oauth-session";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      const sessionResult = await establishOAuthSession(supabase.auth, result.tokens, {
        trace: ({ stage, ok, code, durationMs }) =>
          logAuthStage("oauth_session_setup", {
            ok,
            code: `${stage}:${code}`,
            durationMs,
          }),
      });
      if (!sessionResult.ok) {
        return {
          error: sessionResult.error,
          redirected: false as const,
          sessionPersistenceFailed: true as const,
          sessionErrorCode: sessionResult.code,
        };
      }
      return result;
    },
  },
};
