/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverRouteImport } from './routes/recover'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedBetaConsentRouteImport } from './routes/_authenticated/beta-consent'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips.index'
import { Route as ApiPublicPaddleWebhookRouteImport } from './routes/api/public/paddle-webhook'
import { Route as AuthenticatedTripsIdRouteImport } from './routes/_authenticated/trips.$id'
import { Route as AuthenticatedConsoleWebhookTestRouteImport } from './routes/_authenticated/console.webhook-test'
import { Route as AuthenticatedConsolePromoCodesRouteImport } from './routes/_authenticated/console.promo-codes'
import { Route as AuthenticatedConsoleEventsRouteImport } from './routes/_authenticated/console.events'
import { Route as AuthenticatedConsoleDiagnosticsRouteImport } from './routes/_authenticated/console.diagnostics'
import { Route as AuthenticatedConsoleAnalyticsRouteImport } from './routes/_authenticated/console.analytics'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverRoute = RecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBetaConsentRoute =
  AuthenticatedBetaConsentRouteImport.update({
    id: '/beta-consent',
    path: '/beta-consent',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaddleWebhookRoute = ApiPublicPaddleWebhookRouteImport.update({
  id: '/api/public/paddle-webhook',
  path: '/api/public/paddle-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsIdRoute = AuthenticatedTripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsoleWebhookTestRoute =
  AuthenticatedConsoleWebhookTestRouteImport.update({
    id: '/console/webhook-test',
    path: '/console/webhook-test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsolePromoCodesRoute =
  AuthenticatedConsolePromoCodesRouteImport.update({
    id: '/console/promo-codes',
    path: '/console/promo-codes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsoleEventsRoute =
  AuthenticatedConsoleEventsRouteImport.update({
    id: '/console/events',
    path: '/console/events',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsoleDiagnosticsRoute =
  AuthenticatedConsoleDiagnosticsRouteImport.update({
    id: '/console/diagnostics',
    path: '/console/diagnostics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsoleAnalyticsRoute =
  AuthenticatedConsoleAnalyticsRouteImport.update({
    id: '/console/analytics',
    path: '/console/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/beta-consent': typeof AuthenticatedBetaConsentRoute
  '/events': typeof AuthenticatedEventsRoute
  '/map': typeof AuthenticatedMapRoute
  '/me': typeof AuthenticatedMeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/join/$token': typeof JoinTokenRoute
  '/console/analytics': typeof AuthenticatedConsoleAnalyticsRoute
  '/console/diagnostics': typeof AuthenticatedConsoleDiagnosticsRoute
  '/console/events': typeof AuthenticatedConsoleEventsRoute
  '/console/promo-codes': typeof AuthenticatedConsolePromoCodesRoute
  '/console/webhook-test': typeof AuthenticatedConsoleWebhookTestRoute
  '/trips/$id': typeof AuthenticatedTripsIdRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRoute
  '/beta-consent': typeof AuthenticatedBetaConsentRoute
  '/events': typeof AuthenticatedEventsRoute
  '/map': typeof AuthenticatedMapRoute
  '/me': typeof AuthenticatedMeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/join/$token': typeof JoinTokenRoute
  '/console/analytics': typeof AuthenticatedConsoleAnalyticsRoute
  '/console/diagnostics': typeof AuthenticatedConsoleDiagnosticsRoute
  '/console/events': typeof AuthenticatedConsoleEventsRoute
  '/console/promo-codes': typeof AuthenticatedConsolePromoCodesRoute
  '/console/webhook-test': typeof AuthenticatedConsoleWebhookTestRoute
  '/trips/$id': typeof AuthenticatedTripsIdRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recover': typeof RecoverRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/beta-consent': typeof AuthenticatedBetaConsentRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/join/$token': typeof JoinTokenRoute
  '/_authenticated/console/analytics': typeof AuthenticatedConsoleAnalyticsRoute
  '/_authenticated/console/diagnostics': typeof AuthenticatedConsoleDiagnosticsRoute
  '/_authenticated/console/events': typeof AuthenticatedConsoleEventsRoute
  '/_authenticated/console/promo-codes': typeof AuthenticatedConsolePromoCodesRoute
  '/_authenticated/console/webhook-test': typeof AuthenticatedConsoleWebhookTestRoute
  '/_authenticated/trips/$id': typeof AuthenticatedTripsIdRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/recover'
    | '/reset-password'
    | '/terms'
    | '/app'
    | '/beta-consent'
    | '/events'
    | '/map'
    | '/me'
    | '/settings'
    | '/join/$token'
    | '/console/analytics'
    | '/console/diagnostics'
    | '/console/events'
    | '/console/promo-codes'
    | '/console/webhook-test'
    | '/trips/$id'
    | '/api/public/paddle-webhook'
    | '/trips/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/recover'
    | '/reset-password'
    | '/terms'
    | '/app'
    | '/beta-consent'
    | '/events'
    | '/map'
    | '/me'
    | '/settings'
    | '/join/$token'
    | '/console/analytics'
    | '/console/diagnostics'
    | '/console/events'
    | '/console/promo-codes'
    | '/console/webhook-test'
    | '/trips/$id'
    | '/api/public/paddle-webhook'
    | '/trips'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/recover'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/app'
    | '/_authenticated/beta-consent'
    | '/_authenticated/events'
    | '/_authenticated/map'
    | '/_authenticated/me'
    | '/_authenticated/settings'
    | '/join/$token'
    | '/_authenticated/console/analytics'
    | '/_authenticated/console/diagnostics'
    | '/_authenticated/console/events'
    | '/_authenticated/console/promo-codes'
    | '/_authenticated/console/webhook-test'
    | '/_authenticated/trips/$id'
    | '/api/public/paddle-webhook'
    | '/_authenticated/trips/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoverRoute: typeof RecoverRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiPublicPaddleWebhookRoute: typeof ApiPublicPaddleWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover': {
      id: '/recover'
      path: '/recover'
      fullPath: '/recover'
      preLoaderRoute: typeof RecoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/beta-consent': {
      id: '/_authenticated/beta-consent'
      path: '/beta-consent'
      fullPath: '/beta-consent'
      preLoaderRoute: typeof AuthenticatedBetaConsentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/paddle-webhook': {
      id: '/api/public/paddle-webhook'
      path: '/api/public/paddle-webhook'
      fullPath: '/api/public/paddle-webhook'
      preLoaderRoute: typeof ApiPublicPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/$id': {
      id: '/_authenticated/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof AuthenticatedTripsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/console/webhook-test': {
      id: '/_authenticated/console/webhook-test'
      path: '/console/webhook-test'
      fullPath: '/console/webhook-test'
      preLoaderRoute: typeof AuthenticatedConsoleWebhookTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/console/promo-codes': {
      id: '/_authenticated/console/promo-codes'
      path: '/console/promo-codes'
      fullPath: '/console/promo-codes'
      preLoaderRoute: typeof AuthenticatedConsolePromoCodesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/console/events': {
      id: '/_authenticated/console/events'
      path: '/console/events'
      fullPath: '/console/events'
      preLoaderRoute: typeof AuthenticatedConsoleEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/console/diagnostics': {
      id: '/_authenticated/console/diagnostics'
      path: '/console/diagnostics'
      fullPath: '/console/diagnostics'
      preLoaderRoute: typeof AuthenticatedConsoleDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/console/analytics': {
      id: '/_authenticated/console/analytics'
      path: '/console/analytics'
      fullPath: '/console/analytics'
      preLoaderRoute: typeof AuthenticatedConsoleAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedBetaConsentRoute: typeof AuthenticatedBetaConsentRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedConsoleAnalyticsRoute: typeof AuthenticatedConsoleAnalyticsRoute
  AuthenticatedConsoleDiagnosticsRoute: typeof AuthenticatedConsoleDiagnosticsRoute
  AuthenticatedConsoleEventsRoute: typeof AuthenticatedConsoleEventsRoute
  AuthenticatedConsolePromoCodesRoute: typeof AuthenticatedConsolePromoCodesRoute
  AuthenticatedConsoleWebhookTestRoute: typeof AuthenticatedConsoleWebhookTestRoute
  AuthenticatedTripsIdRoute: typeof AuthenticatedTripsIdRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedBetaConsentRoute: AuthenticatedBetaConsentRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedConsoleAnalyticsRoute: AuthenticatedConsoleAnalyticsRoute,
  AuthenticatedConsoleDiagnosticsRoute: AuthenticatedConsoleDiagnosticsRoute,
  AuthenticatedConsoleEventsRoute: AuthenticatedConsoleEventsRoute,
  AuthenticatedConsolePromoCodesRoute: AuthenticatedConsolePromoCodesRoute,
  AuthenticatedConsoleWebhookTestRoute: AuthenticatedConsoleWebhookTestRoute,
  AuthenticatedTripsIdRoute: AuthenticatedTripsIdRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecoverRoute: RecoverRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiPublicPaddleWebhookRoute: ApiPublicPaddleWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
