/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated/trips.index'
import { Route as ApiPublicPaddleWebhookRouteImport } from './routes/api/public/paddle-webhook'
import { Route as AuthenticatedTripsIdRouteImport } from './routes/_authenticated/trips.$id'
import { Route as AuthenticatedConsoleWebhookTestRouteImport } from './routes/_authenticated/console.webhook-test'
import { Route as AuthenticatedConsolePromoCodesRouteImport } from './routes/_authenticated/console.promo-codes'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPaddleWebhookRoute = ApiPublicPaddleWebhookRouteImport.update({
  id: '/api/public/paddle-webhook',
  path: '/api/public/paddle-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTripsIdRoute = AuthenticatedTripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsoleWebhookTestRoute =
  AuthenticatedConsoleWebhookTestRouteImport.update({
    id: '/console/webhook-test',
    path: '/console/webhook-test',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConsolePromoCodesRoute =
  AuthenticatedConsolePromoCodesRouteImport.update({
    id: '/console/promo-codes',
    path: '/console/promo-codes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/events': typeof AuthenticatedEventsRoute
  '/map': typeof AuthenticatedMapRoute
  '/me': typeof AuthenticatedMeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/join/$token': typeof JoinTokenRoute
  '/console/promo-codes': typeof AuthenticatedConsolePromoCodesRoute
  '/console/webhook-test': typeof AuthenticatedConsoleWebhookTestRoute
  '/trips/$id': typeof AuthenticatedTripsIdRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/events': typeof AuthenticatedEventsRoute
  '/map': typeof AuthenticatedMapRoute
  '/me': typeof AuthenticatedMeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/join/$token': typeof JoinTokenRoute
  '/console/promo-codes': typeof AuthenticatedConsolePromoCodesRoute
  '/console/webhook-test': typeof AuthenticatedConsoleWebhookTestRoute
  '/trips/$id': typeof AuthenticatedTripsIdRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/join/$token': typeof JoinTokenRoute
  '/_authenticated/console/promo-codes': typeof AuthenticatedConsolePromoCodesRoute
  '/_authenticated/console/webhook-test': typeof AuthenticatedConsoleWebhookTestRoute
  '/_authenticated/trips/$id': typeof AuthenticatedTripsIdRoute
  '/api/public/paddle-webhook': typeof ApiPublicPaddleWebhookRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/events'
    | '/map'
    | '/me'
    | '/settings'
    | '/join/$token'
    | '/console/promo-codes'
    | '/console/webhook-test'
    | '/trips/$id'
    | '/api/public/paddle-webhook'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/events'
    | '/map'
    | '/me'
    | '/settings'
    | '/join/$token'
    | '/console/promo-codes'
    | '/console/webhook-test'
    | '/trips/$id'
    | '/api/public/paddle-webhook'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/reset-password'
    | '/_authenticated/events'
    | '/_authenticated/map'
    | '/_authenticated/me'
    | '/_authenticated/settings'
    | '/join/$token'
    | '/_authenticated/console/promo-codes'
    | '/_authenticated/console/webhook-test'
    | '/_authenticated/trips/$id'
    | '/api/public/paddle-webhook'
    | '/_authenticated/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiPublicPaddleWebhookRoute: typeof ApiPublicPaddleWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/paddle-webhook': {
      id: '/api/public/paddle-webhook'
      path: '/api/public/paddle-webhook'
      fullPath: '/api/public/paddle-webhook'
      preLoaderRoute: typeof ApiPublicPaddleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trips/$id': {
      id: '/_authenticated/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof AuthenticatedTripsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/console/webhook-test': {
      id: '/_authenticated/console/webhook-test'
      path: '/console/webhook-test'
      fullPath: '/console/webhook-test'
      preLoaderRoute: typeof AuthenticatedConsoleWebhookTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/console/promo-codes': {
      id: '/_authenticated/console/promo-codes'
      path: '/console/promo-codes'
      fullPath: '/console/promo-codes'
      preLoaderRoute: typeof AuthenticatedConsolePromoCodesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedConsolePromoCodesRoute: typeof AuthenticatedConsolePromoCodesRoute
  AuthenticatedConsoleWebhookTestRoute: typeof AuthenticatedConsoleWebhookTestRoute
  AuthenticatedTripsIdRoute: typeof AuthenticatedTripsIdRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedConsolePromoCodesRoute: AuthenticatedConsolePromoCodesRoute,
  AuthenticatedConsoleWebhookTestRoute: AuthenticatedConsoleWebhookTestRoute,
  AuthenticatedTripsIdRoute: AuthenticatedTripsIdRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiPublicPaddleWebhookRoute: ApiPublicPaddleWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
