// This file is automatically generated. Do not edit it directly.
//
// LOAD-BEARING DEVIATION FROM GENERATOR (Google OAuth callback ownership):
// `flowType: "pkce"` + `detectSessionInUrl: false` are required so that
// `/auth/callback` is the SINGLE owner of the one-time PKCE authorization
// code exchange. If the generator regenerates this file, re-apply the two
// `auth` options below. See docs/runbooks/google-oauth-callback.md.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      // PKCE — `/auth/callback` is the single owner of the code-for-session
      // exchange. `detectSessionInUrl` must stay OFF: with it on, the SDK
      // races the callback route to consume the one-time authorization code
      // and either the callback fails ("code already used") or a stray
      // `/auth?code=…` landing silently consumes it and never reaches the
      // callback owner. See docs/runbooks/google-oauth-callback.md.
      flowType: "pkce",
      detectSessionInUrl: false,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
